{% set version = "0.1.0" %}
{% set name = "hgvsParseR" %}
{% set sha256 = "a540ae0ec48e892f0e31d50a2c33d5b6d477cdf9b1d03612361acb2da4fcd5ab" %}

package:
  name: {{ name|lower }}
  version: '{{ version }}'

source:
  url: https://github.com/VariantEffect/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  script: '$R CMD INSTALL --build .'

requirements:
  host:
    - r-base
    - r-devtools
    
  run:
    - r-base
    - r-devtools

test:
  commands:
    - $R -e "library('{{ name }}')"

about:
  home: https://github.com/VariantEffect/hgvsParseR
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: {{ name }}
  doc_url: https://github.com/VariantEffect/hgvsParseR
  dev_url: https://github.com/VariantEffect/hgvsParseR